"<!doctype html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"\t<style>\n"
"\t\ttable.dirs {\n"
"\t\t\tborder-collapse: collapse;\n"
"\t\t\twidth: 100%;\n"
"\t\t}\n"
"\t\ttable.dirs th, table.dirs td {\n"
"\t\t\ttext-align: left;\n"
"\t\t\tpadding: 4px;\n"
"\t\t\tborder-bottom: 1px solid #DDD;\n"
"\t\t}\n"
"\t\ttable.dirs tr:nth-child(even) {background-color: #525c5c;}\n"
"\t\ttable.dirs tr:nth-child(odd) {background-color: #657272;}\n"
"\t\ttable.dirs tr:hover {background-color: #6a7575;}\n"
"\t\t@font-face {\n"
"      \t\tfont-family: 'C64 Pro Mono';\n"
"      \t\tsrc: url('web/C64_Pro_Mono.ttf') format('truetype');\n"
"      \t\tfont-weight: normal;\n"
"      \t\tfont-style: normal;\n"
"    \t}\n"
"\t\ta:link {\n"
" \t\t\tcolor: rgb(255, 255, 255);\n"
"  \t\t\tbackground-color: transparent;\n"
"  \t\t\ttext-decoration: none;\n"
"\t\t}\t\t\n"
"\t\ta:visited {\n"
" \t\t\tcolor: rgb(247, 239, 239);\n"
"  \t\t\tbackground-color: transparent;\n"
"  \t\t\ttext-decoration: none;\n"
"\t\t}\n"
"\t\ta:active {\n"
" \t\t\tcolor: rgb(238, 255, 0);\n"
"  \t\t\tbackground-color: transparent;\n"
"  \t\t\ttext-decoration: none;\n"
"\t\t}\n"
"\t\ta:hover {\n"
" \t\t\tcolor: rgb(238, 255, 0);\n"
"  \t\t\tbackground-color: transparent;\n"
"  \t\t\ttext-decoration: none;\n"
"\t\t}\n"
"\t</style>\n"
"\t<meta charset=\"utf-8\">\n"
"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/darkly/bootstrap.min.css\"\n"
"\t\tintegrity=\"sha512-8lE+UgnY2CgbE+WDsGwSwAiMOswuRYm11jXYV5KWH6XfSDAzrdRMbPQDpCwzVjJbe9quHrNNPV6N/llRKnw5Hg==\"\n"
"\t\tcrossorigin=\"anonymous\" />\n"
"\t<link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n"
"\t<title>Pi1541 Web-Interface</title>\n"
"</head>\n"
"\n"
"<body>\n"
"\t<br />\n"
"\t<div class=\"container\">\n"
"\t\t<div class=\"container\" style=\"background-color: #000000; text-align: center; padding-bottom: 8px; padding-top: 8px;\">\n"
"\t\t\t<table>\n"
"\t\t\t\t<td>\n"
"\t\t\t\t\t<h1 style=\"text-align:left\">Pi1541 WebUI</h1>\n"
"\t\t\t\t\t<p style=\"text-align:left\">by pottendo</p>\n"
"\t\t\t\t\t<h3 style=\"text-align:left\">Drives</h3>\n"
"\t\t\t\t</td>\n"
"\t\t\t\t<td>\n"
"\t\t\t\t\t<a href=\"index.html\">\n"
"\t\t\t\t\t\t<img src=\"/pi1541-logo.png\" style=\"height: 160px; width: 720px; cursor:pointer;\" />\n"
"\t\t\t\t\t</a>\n"
"\t\t\t\t</td>\n"
"\t\t\t</table>\n"
"\t\t</div>\n"
"\t\t<div class=\"container bg-dark\">\n"
"\t\t\t<br />\n"
"\t\t\t<!--\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\"> \n"
"\t\t\t\t\t<h3 style=\"text-align: left\">Menu</h3>\t-->\n"
"\t\t\t<table style=\"width: 100%;\">\n"
"\t\t\t\t<tr>\n"
"\t\t\t\t\t<td>\n"
"\t\t\t\t\t\t<div style=\"display: flex; justify-content: space-between; width: 100%;\">\n"
"\t\t\t\t\t\t\t<a href=\"index.html\"><input type=\"submit\" class=\"btn btn-success\" \n"
"\t\t\t\t\t\t\t\t\tvalue=\"Upload/Manage SDCard\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"mount-imgs.html\"><input type=\"submit\" class=\"btn btn-success\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Mount Images\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"drives.html\"><input type=\"submit\" class=\"btn btn-success\" style=\"font-weight: bold; color: black;\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Drives\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"edit-config.html\"><input type=\"submit\" class=\"btn btn-success\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Change Config\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"update.html\"><input type=\"submit\" class=\"btn btn-success\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Update Pi1541\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"logger.html\"><input type=\"submit\" class=\"btn btn-success\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Logging\" /></a>\n"
"\t\t\t\t\t\t\t<a href=\"reset.html\"><input type=\"submit\" class=\"btn btn-success\" onClick=\"return delConfirm(event)\"\n"
"\t\t\t\t\t\t\t\t\tvalue=\"Reset Pi1541\" /></a>\n"
"\t\t\t\t\t\t</div>\n"
"\t\t\t\t\t</td>\n"
"\t\t\t\t</tr>\n"
"\t\t\t</table>\n"
"\t\t\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\">\n"
"            <table style=\"width: 100%;\">\n"
"                <tr>\n"
"                    <td>\n"
"                        <div style=\"display: flex; justify-content: space-between; width: 100%;\">\n"
"                            <h4 style=\"text-align: left\">Status</h4>\n"
"                            <div style=\"text-align: right\" id=\"externalText\">Loading...</div>\n"
"                        </div>\n"
"                    </td>\n"
"                </tr>\n"
"                <tr>\n"
"                    <td>\n"
"                        <div style=\"text-align:right;\">\n"
"                            <a href=\"drives.html?[toggleDrive]&\">\n"
"                                <button type=\"button\" class=\"btn btn-success\">Select Drive</button>\n"
"                            </a>\n"
"                        </div>\n"
"                    </td>\n"
"                </tr>\n"
"            </table>\n"
"\t\t\t<p>%s</p>\n"
"\t\t\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\">\n"
"            <h3 style=\"text-align: left;\">Drive Controls</h3>\n"
"\n"
"            <table style=\"width: 100%;\">\n"
"                <tr>\n"
"                    <th>Drive 0</th>\n"
"                    <th>Drive 1</th>\n"
"                </tr>\n"
"                <tr>\n"
"                    <td>Drive ID: %d</td>\n"
"                    <td>Drive ID: %d</td>\n"
"                </tr>\n"
"                <tr>\n"
"                    <td>\n"
"                        <table style=\"width: 100%;\">\n"
"                            <tr>\n"
"                                <td>\n"
"                                    <div style=\"display: flex; justify-content: left; width: 100%;\"></div>\n"
"                                    <a href=\"drives.html?[switchDrive]&0&%s&\">\n"
"                                        <button type=\"button\" class=\"btn btn-success\">Switch %s</button>\n"
"                                    </a>\n"
"                                    <a href=\"mount-imgs.html?&&%d&\">\n"
"                                        <button type=\"button\" class=\"btn btn-success\">Mount</button>\n"
"                                    </a>\n"
"                                    </div>\n"
"                                </td>\n"
"                            </tr>\n"
"                        </table>\n"
"                    </td>\n"
"                    <td>\n"
"                        <table style=\"width: 100%;\">\n"
"                            <tr>\n"
"                                <td>\n"
"                                    <div style=\"display: flex; justify-content: left; width: 100%;\">\n"
"                                        <a href=\"drives.html?[switchDrive]&1&%s&\">\n"
"                                            <button type=\"button\" class=\"btn btn-success\">Switch %s</button>\n"
"                                        </a>\n"
"                                        <a href=\"mount-imgs.html?&&%d&\">\n"
"                                            <button type=\"button\" class=\"btn btn-success\">Mount</button>\n"
"                                        </a>\n"
"                                    </div>\n"
"                                </td>\n"
"                            </tr>\n"
"                        </table>\n"
"                    </td>\n"
"                </tr>\n"
"            </table>\n"
"\t\t</div>\n"
"\t\t<p class=\"small\">%s, %s</p>\n"
"\t\t<p class=\"small\">Find the Pi1541 project resources here <a href=\"https://cbm-pi1541.firebaseapp.com/\"\n"
"\t\t\t\ttarget=\"_blank\">Pi1541 firebase</a>.</p>\n"
"\t\t<p class=\"small\">Find the pottendo-Pi1541 project resources here\n"
"\t\t\t<a href=\"https://github.com/pottendo/pottendo-Pi1541\" target=\"_blank\">pottendo-Pi1541</a>.</p>\n"
"\t\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\n"
"\t\t\tintegrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\t\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\n"
"\t\t\tintegrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\t\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"\n"
"\t\t\tintegrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\t\t<script>\n"
"\t\t\tfunction delConfirm(envent) {\n"
"\t\t\t  \tif (confirm(\"Are you sure?\"))\n"
"\t\t\t\t  \treturn true;\n"
"\t\t\t\telse \n"
"\t\t\t\t{\n"
"\t\t\t\t\tevent.preventDefault();\n"
"\t\t\t\t  \treturn false;\n"
"\t\t\t\t}\n"
"\t\t\t};\n"
"\t\t</script>\n"
"\t\t<script>\n"
"\t\t\tfetch('/pistats.html')\n"
"\t\t\t  .then(response => {\n"
"\t\t\t\tif (!response.ok) throw new Error(\"Network error\");\n"
"\t\t\t\treturn response.text();\n"
"\t\t\t  })\n"
"\t\t\t  .then(html => {\n"
"\t\t\t\tdocument.getElementById('externalText').innerHTML = html;\n"
"\t\t\t  })\n"
"\t\t\t  .catch(err => {\n"
"\t\t\t\tdocument.getElementById('externalText').textContent = \"Failed to load content.\";\n"
"\t\t\t\tconsole.error(err);\n"
"\t\t\t  });\n"
"\t\t</script>\n"
"\t</div>\n"
"</body>\n"
"\t\t\n"
"</html>            "