"<!doctype html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"\t<style>\n"
"\t\ttable {\n"
"\t\t  border-collapse: collapse;\n"
"\t\t  width: 100%;\n"
"\t\t}\n"
"\t\tth, td {\n"
"\t\t  text-align: left;\n"
"\t\t  padding: 4px;\n"
"\t\t  border-bottom: 1px solid #DDD;\t\t\t\t\n"
"\t\t}\n"
"\t\ttr:nth-child(even) {\n"
"\t\t  background-color: #525c5c;\n"
"\t\t}\n"
"\t\ttr:nth-child(odd) {\n"
"\t\t  background-color: #657272;\n"
"\t\t}\n"
"\t\ttr:hover {background-color: #6a7575;}\n"
"\t\t</style>\n"
"\t<meta charset=\"utf-8\">\n"
"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/darkly/bootstrap.min.css\"\n"
"\t\tintegrity=\"sha512-8lE+UgnY2CgbE+WDsGwSwAiMOswuRYm11jXYV5KWH6XfSDAzrdRMbPQDpCwzVjJbe9quHrNNPV6N/llRKnw5Hg==\"\n"
"\t\tcrossorigin=\"anonymous\" />\n"
"\t<link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n"
"\t<title>Pi1541 Web-Interface Configuration & Update</title>\n"
"</head>\n"
"\n"
"<body>\n"
"\t<br />\n"
"\t<div class=\"container\">\n"
"\t\t<div class=\"container\" style=\"background-color: #3a3a3a; text-align: center; padding-bottom: 8px; padding-top: 8px;\">\n"
"\t\t\t<img src=\"/pi1541-logo.png\" style=\"height: 256px; width: 1024px;\" />\n"
"\t\t</div>\n"
"\t\t<div class=\"container bg-dark\">\n"
"\t\t\t<br />\n"
"\t\t\t<h1 style=\"text-align:center\">Pi1541 Edit Configuration</h1>\n"
"\t\t\t<p style=\"text-align:center\"> by pottendo</p>\n"
"\t\t\t<p>%s</p>\n"
"\t\t\t<form action=\"/edit-config.html\" method=\"post\" name=\"options-form\" accept-charset=\"UTF-8\" enctype=\"multipart/form-data\">\n"
"\t\t\t\t<div class=\"form-group\">\n"
"\t\t\t\t\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\">\n"
"\t\t\t\t\t<h4 style=\"text-align:left\"><i>options.txt</i></h2>\n"
"\t\t\t\t\t<label for=\"textarea_options\">Edit configuration file SD:/options.txt</label>\n"
"\t\t    \t\t<textarea class=\"form-control\" name=\"options.txt\" id=\"textarea_options\" rows=\"10\" \n"
"\t\t\t\t\t\t\t  style=\"background-color: #4d4d4d; font-family: monospace; color: #ECFFDC;\">%s</textarea>\n"
"\t\t\t\t\t<br/>\n"
"\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"Update options.txt\" />\n"
"\t\t\t\t</div>\n"
"\t\t\t</form>\n"
"\t\t\t<form action=\"/edit-config.html\" method=\"post\" name=\"config-form\" accept-charset=\"UTF-8\" enctype=\"multipart/form-data\">\n"
"\t\t\t\t\t<div class=\"form-group\">\n"
"\t\t\t\t\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\">\n"
"\t\t\t\t\t<h4 style=\"text-align:left\"><i>config.txt</i></h2>\n"
"\t\t\t\t\t<label for=\"textarea_config\">Edit configuration file SD:/config.txt</label>\n"
"\t\t    \t\t<textarea class=\"form-control\" name=\"config.txt\" id=\"textarea_config\" rows=\"10\" \n"
"\t\t\t\t\t\t\t  style=\"background-color: #4d4d4d; font-family: monospace; color: #ECFFDC;\">%s</textarea>\n"
"\t\t\t\t\t<br/>\n"
"\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"Update config.txt\" />\n"
"\t\t\t\t</div>\n"
"\t\t\t</form>\n"
"\t\t\t<hr style=\"border: 1px solid rgb(155, 155, 155); margin: 8px auto;\">\n"
"\t\t\t<form action=\"index.html\" method=\"post\" name=\"back-button\" enctype=\"multipart/form-data\">\n"
"\t\t\t\t<div class=\"form-group\">\n"
"\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"Back to main page\" />\n"
"\t\t\t\t\t<br/><br/>\n"
"\t\t\t\t</div>\n"
"\t\t\t</form>\n"
"\t\t</div>\n"
"\t\t<p class=\"small\">%s</p>\n"
"\t\t<p class=\"small\">Find the Pi1541 project resources here <a href=\"https://cbm-pi1541.firebaseapp.com/\"\n"
"\t\t\t\ttarget=\"_blank\">Pi1541 firebase</a>.</p>\n"
"\t\t<p class=\"small\">Find the pottendo-Pi1541 project resources here <a\n"
"\t\t\t\thref=\"https://github.com/pottendo/pottendo-Pi1541\" target=\"_blank\">pottendo-Pi1541</a>.</p>\n"
"\t\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\n"
"\t\t\tintegrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\t\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\n"
"\t\t\tintegrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\t\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"\n"
"\t\t\tintegrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\"\n"
"\t\t\tcrossorigin=\"anonymous\"></script>\n"
"\n"
"\t\t<script>\n"
"\t\t\t$(document).ready(function () {\n"
"\t\t\t\tdocument.querySelector('.custom-file-input1').addEventListener('change', function (e) {\n"
"\t\t\t\t\tvar fileName = document.getElementById(\"UploadKernel\").files[0].name;\n"
"\t\t\t\t\tvar nextSibling = e.target.nextElementSibling;\n"
"\t\t\t\t\tnextSibling.innerText = fileName;\n"
"\t\t\t\t});\n"
"\t\t\t\tdocument.querySelector('.custom-file-input2').addEventListener('change', function (e) {\n"
"\t\t\t\t\tvar fileName = document.getElementById(\"UploadOptions\").files[0].name;\n"
"\t\t\t\t\tvar nextSibling = e.target.nextElementSibling;\n"
"\t\t\t\t\tnextSibling.innerText = fileName;\n"
"\t\t\t\t});\n"
"\t\t\t});\n"
"\t\t</script>\n"
"\n"
"\t</div>\n"
"</body>\n"
"\n"
"</html>"