#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

CIRCLEBASE ?= ../../circle-stdlib
include $(CIRCLEBASE)/Config.mk

PI1541OBS = $(COMMON_OBJS)
OBJS = $(CIRCLE_OBJS) $(PI1541OBS)

include $(CIRCLEHOME)/Rules.mk

CFLAGS += -D__CIRCLE__ -I. \
	  -Wno-psabi -Wno-write-strings -Wno-unused-variable -Wno-unused-but-set-variable -Wno-address \
	  -Wno-format-truncation -Wno-stringop-truncation -Wno-unused-function \
	  -DRPI3=1 $(XFLAGS)

#AFLAGS = -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -marm -DRPI3=1 -DDEBUG=1

# -mno-unaligned-access \

INCLUDE := $(CIRCLE_STDLIB_INCLUDES) $(INCLUDE)

LIBS := $(CIRCLEHOME)/addon/wlan/hostap/wpa_supplicant/libwpa_supplicant.a \
	$(CIRCLEHOME)/addon/wlan/libwlan.a \
	$(CIRCLEHOME)/lib/sound/libsound.a \
	$(CIRCLE_STDLIB_LIBS)

EXTRACLEAN = ${OBJS:.o=.d} ${SKVIC20OBJS:.o=.d} $(SKVIC20OBJS) $(RADOBJS) $(OLED) *.img *.lst *.map *.elf version.h

-include $(DEPS)
